# Generated by Django 4.1.7 on 2023-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
