# Generated by Django 4.1.7 on 2023-03-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_customermessage_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
