# Generated by Django 4.1.7 on 2023-03-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
